"""Print the canonical DDL.

``python scripts/print_schema.py > migrations/001_init.sql`` regenerates the
file you paste into the Supabase SQL editor.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
os.environ.setdefault("DATABASE_URL", "postgresql://localhost/placeholder")

from app.db import schema_statements  # noqa: E402
from app.utils.config import Settings  # noqa: E402

HEADER = """-- Hive Mind Memory Server — schema.
-- Generated by scripts/print_schema.py. Applied automatically on startup when
-- AUTO_MIGRATE=true; run it by hand in the Supabase SQL editor otherwise.
"""


ALTERNATIVE = """-- Alternative ANN index. hnsw (above) is the default because an ivfflat
-- index built before the table has data has no clusters to search and then
-- silently returns fewer rows than requested. If you prefer ivfflat, set
-- VECTOR_INDEX_TYPE=ivfflat, run the statement below instead of the hnsw one,
-- and REINDEX it once you have a few thousand rows.
--
-- {statement}"""


def main() -> None:
    print(HEADER)
    for statement in schema_statements():
        print(statement.rstrip(";") + ";\n")

    other = "ivfflat" if Settings().vector_index_type == "hnsw" else "hnsw"
    alternative = next(
        line
        for line in schema_statements(Settings(vector_index_type=other))
        if "USING " + other in line
    )
    print(ALTERNATIVE.format(statement=alternative))


if __name__ == "__main__":
    main()
