-- Hive Mind Memory Server — schema.
-- Generated by scripts/print_schema.py. Applied automatically on startup when
-- AUTO_MIGRATE=true; run it by hand in the Supabase SQL editor otherwise.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS memory (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project      TEXT NOT NULL,
    type         TEXT NOT NULL,
    title        TEXT NOT NULL,
    content      TEXT NOT NULL,
    tags         TEXT[] NOT NULL DEFAULT '{}',
    source       TEXT,
    metadata     JSONB NOT NULL DEFAULT '{}'::jsonb,
    content_hash VARCHAR(64) NOT NULL,
    embedding    VECTOR(384) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS memory_project_idx ON memory (project);

CREATE INDEX IF NOT EXISTS memory_type_idx ON memory (type);

CREATE INDEX IF NOT EXISTS memory_created_at_idx ON memory (created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS memory_project_hash_key ON memory (project, content_hash);

CREATE INDEX IF NOT EXISTS memory_fts_idx ON memory USING gin (to_tsvector('english', title || ' ' || content));

CREATE INDEX IF NOT EXISTS memory_embedding_hnsw_idx ON memory USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- Alternative ANN index. hnsw (above) is the default because an ivfflat
-- index built before the table has data has no clusters to search and then
-- silently returns fewer rows than requested. If you prefer ivfflat, set
-- VECTOR_INDEX_TYPE=ivfflat, run the statement below instead of the hnsw one,
-- and REINDEX it once you have a few thousand rows.
--
-- CREATE INDEX IF NOT EXISTS memory_embedding_ivfflat_idx ON memory USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
